Models/Figura.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace firstApp.Models
{ public class Figura
    
        {
[Key]
public int figuraId{get; set;}

[Required(ErrorMessage ="Nombre es requerido")]
[Display(Name ="Nombre")]
public string  nombre {get; set;}

[Required(ErrorMessage ="lados es requerido")]
[Display(Name ="lados")]
public string  lados {get; set;}

[Required(ErrorMessage ="angulo es requerido")]
[Display(Name ="angulo")]
public string angulo {get; set;}

//referencia para NombreFigura
[Required(ErrorMessage ="NombreFigura es requerido")]
[Display(Name ="NombreFigura")]
public int AutorFiguraID{get; set;}
public AutorFigura AutorFiguras {set; get;}

        }
}

Controllers/AutorFiguraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using firstApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace firstApp.Controllers
{
    [Authorize]

    public class AutorFiguraController : Controller
    {
        private readonly ejemplocontext _context;

        public AutorFiguraController(ejemplocontext context)
        {
            _context = context;
        }

        // GET: AutorFigura
        public async Task<IActionResult> Index()
        {
            return View(await _context.AutorFigura.ToListAsync());
        }

        // GET: AutorFigura/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autorFigura = await _context.AutorFigura
                .FirstOrDefaultAsync(m => m.AutorFiguraID == id);
            if (autorFigura == null)
            {
                return NotFound();
            }

            return View(autorFigura);
        }

        // GET: AutorFigura/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AutorFigura/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AutorFiguraID,Nombre,Apellido,Correo,Genero,Direccion")] AutorFigura autorFigura)
        {
            if (ModelState.IsValid)
            {
                _context.Add(autorFigura);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(autorFigura);
        }

        // GET: AutorFigura/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autorFigura = await _context.AutorFigura.FindAsync(id);
            if (autorFigura == null)
            {
                return NotFound();
            }
            return View(autorFigura);
        }

        // POST: AutorFigura/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AutorFiguraID,Nombre,Apellido,Correo,Genero,Direccion")] AutorFigura autorFigura)
        {
            if (id != autorFigura.AutorFiguraID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(autorFigura);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutorFiguraExists(autorFigura.AutorFiguraID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(autorFigura);
        }

        // GET: AutorFigura/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autorFigura = await _context.AutorFigura
                .FirstOrDefaultAsync(m => m.AutorFiguraID == id);
            if (autorFigura == null)
            {
                return NotFound();
            }

            return View(autorFigura);
        }

        // POST: AutorFigura/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var autorFigura = await _context.AutorFigura.FindAsync(id);
            _context.AutorFigura.Remove(autorFigura);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AutorFiguraExists(int id)
        {
            return _context.AutorFigura.Any(e => e.AutorFiguraID == id);
        }
    }
}

Controllers/FiguraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using firstApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace firstApp.Controllers
{
    [Authorize]
    
    public class FiguraController : Controller
    {
        private readonly ejemplocontext _context;

        public FiguraController(ejemplocontext context)
        {
            _context = context;
        }

        // GET: Figura
        public async Task<IActionResult> Index()
        {
            var ejemplocontext = _context.Figura.Include(f => f.AutorFiguras);
            return View(await ejemplocontext.ToListAsync());
        }

        // GET: Figura/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var figura = await _context.Figura
                .Include(f => f.AutorFiguras)
                .FirstOrDefaultAsync(m => m.figuraId == id);
            if (figura == null)
            {
                return NotFound();
            }

            return View(figura);
        }

        // GET: Figura/Create
        public IActionResult Create()
        {
            ViewData["AutorFiguraID"] = new SelectList(_context.Set<AutorFigura>(), "AutorFiguraID", "Apellido");
            return View();
        }

        // POST: Figura/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("figuraId,nombre,lados,angulo,AutorFiguraID")] Figura figura)
        {
            if (ModelState.IsValid)
            {
                _context.Add(figura);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AutorFiguraID"] = new SelectList(_context.Set<AutorFigura>(), "AutorFiguraID", "Apellido", figura.AutorFiguraID);
            return View(figura);
        }

        // GET: Figura/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var figura = await _context.Figura.FindAsync(id);
            if (figura == null)
            {
                return NotFound();
            }
            ViewData["AutorFiguraID"] = new SelectList(_context.Set<AutorFigura>(), "AutorFiguraID", "Apellido", figura.AutorFiguraID);
            return View(figura);
        }

        // POST: Figura/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("figuraId,nombre,lados,angulo,AutorFiguraID")] Figura figura)
        {
            if (id != figura.figuraId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(figura);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FiguraExists(figura.figuraId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AutorFiguraID"] = new SelectList(_context.Set<AutorFigura>(), "AutorFiguraID", "Apellido", figura.AutorFiguraID);
            return View(figura);
        }

        // GET: Figura/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var figura = await _context.Figura
                .Include(f => f.AutorFiguras)
                .FirstOrDefaultAsync(m => m.figuraId == id);
            if (figura == null)
            {
                return NotFound();
            }

            return View(figura);
        }

        // POST: Figura/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var figura = await _context.Figura.FindAsync(id);
            _context.Figura.Remove(figura);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FiguraExists(int id)
        {
            return _context.Figura.Any(e => e.figuraId == id);
        }
    }
}

Views/Shared/_Figura.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"] - Figura</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SigInManager


 <!-- Page Wrapper -->
    <div id="wrapper">
@if(SigInManager.IsSignedIn(User))
{

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Homer" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-shapes"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Figura</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Figura
            </div>

            <!-- Nav Item - Pages Collapse Menu Figuras -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-folder-open"></i>
                    <span>Archivo</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Acciones:</h6>
                        <a class="collapse-item" asp-controller="Figura" asp-action="Create">Nueva Figura</a>
                        <a class="collapse-item" asp-controller="Figura" asp-action="Index">Lista de Figuras</a>
                        
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-folder-open"></i>
                    <span>AutorFigura</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">AutorFigura:</h6>
                        <a class="collapse-item" asp-controller="AutorFigura" asp-action="Create">Nuevo Autor</a>
                        <a class="collapse-item" asp-controller="AutorFigura" asp-action="Index">Lista de Autores</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Personal -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Personal" asp-action="Index"> 
                    <i class="far fa-user"></i>
                    <span>Personal</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
}
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
 @if(SigInManager.IsSignedIn(User)){

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                       
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                                    @User.Identity.Name
                                    </span>
                                <img class="img-profile rounded-circle"
                                    src="img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/PersonalData" >
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                               
                               
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>
 }
                </nav>
                <!-- End of Topbar -->
 
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- en este espacio se renderizaran las vistas-->
                  @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Programacion Computacional I</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

  
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/chart-area-demo.js"></script>
    <script src="~/js/demo/chart-pie-demo.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - firstApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">firstApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personal" asp-action="Index">Personal</a>
                        </li>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - firstApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>